### PR TITLE
Make Pony's codebase PEP8 compilent

### LINKED ISSUE #184: The code is not maintained based on PEP-8
A brilliant piece of work, but it has too ugly codes.

Contributing on this project is so painful.

Could you please accept the pull requests about PEP-8 coding style optimizations?
it may make huge changes on the code, but not on logic.

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #184.

### CODE REVIEW

**Comment by pylover** [comment]
The result seems good.

**Comment by thedrow** [comment]
So let's merge this ASAP before we begin any other development.
I'll make the rest of the breaking changes as we reach for 1.0.

**Comment by andreymal** [comment]
I think it can't be merged, because perhaps developers have many local changes not published in this repository

**Comment by thedrow** [comment]
I'll close it for now.

**Pull request closed without merging**
