### PR TITLE
fixed code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/pony/issues/?category=recommended).

### Summary of changes:

- Use literal syntax to create data structure.
> It is unnecessary to use a list or tuple literal within a call to tuple, list, set, or dict since there is a literal syntax for these types.
- Use identity check for comparison with True
> This change gives minor performance boost.
- Remove unnecessary use of comprehension
> This change improves performance and readability.
- Remove unnecessary generator
> Code cleanup.
- Use `is` to compare type of objects
> It is recommended to use identity test ( is ) instead of equality test ( == ) when you need to compare types of two objects.
- Add .deepsource.toml config
> contains configuration to integrate DeepSource.

### CODE REVIEW

**Comment by withshubh** [comment]
Hi @kozlovsky :wave: 

Please have a :eyes: at this PR! :sparkles:

**Comment by withshubh** [comment]
@kozlovsky :wave: please have a look :eyes:

**Comment by withshubh** [comment]
@kozlovsky @amalashkevich :wave: please review this PR!

**Comment by sashaaero** [comment]
Hello! 
Thanks for your submission and sorry for long reply.
Unfortunately we cannot accept this change because it affects files that will be removed in a next release.

**Pull request closed without merging**
