### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by kuanhulio**
These commits add support for Python 3.10.

### CODE REVIEW

**Comment by farzadmf** [comment]
Wow, has been open for more than 1 month!

**Comment by baldurmen** [comment]
This cannot be merged, since Pony isn't actually compatible with Python 3.9. See https://github.com/ponyorm/pony/issues/598

**Comment by farzadmf** [comment]
So, I guess time to find another ORM library unfortunately

**Comment by sashaaero** [comment]
Hello. 
This is not nearly a percent of work that needs to be done to support 3.10.
You can see progress started here -  https://github.com/ponyorm/pony/commits/py_3_10_dev

**Comment by cmacht** [comment]
This has become obsolete with the [release of PonyORM 0.7.15rc1](https://github.com/ponyorm/pony/releases/tag/v0.7.15rc1).

**Pull request closed without merging**
