### PR TITLE
Support Python 3.9

### LINKED ISSUE #514: Python 3.9
A collaborator recently added testing on the beta of 3.9 to the mutmut Travis build and it fails be use pony doesn't allow it. Seems like an unnecessary restriction?

### LINKED ISSUE #530: Please add support for Python 3.9
Python 3.9 is really close to the final release, and apparently supporting it requires a lot of work in Pony (e.g. because Python changed its AST a lot). Could you please consider starting to work on that?

### LINKED ISSUE #562: Setup do not support Python 3.9
Is it possible to modify pony/setup.py to include Python 3.9 ?

### PR DESCRIPTION
**Pull request by tbabej**
Expand the list of supported versions of Python to include newly released Python 3.9.

Resolves #514.
Resolves #530.
Resolves #562.

### CODE REVIEW

**Comment by andreymal** [comment]
Did you test Pony with Python 3.9?

**Comment by tbabej** [comment]
Runs just fine with my application (that admittedly uses only a subset of the functionality). Running the tests in `pony/orm/tests` (which I only discovered now), we do get some additional failures of the tests, mostly related to `CONTAINS_OP` and `IS_OP`. I think it has to do with the following change in Python 3.9:

https://twitter.com/raymondh/status/1262181085665886208

**Comment by tbabej** [comment]
Down to 2 failing tests. The only new bytecode that is causing problems seems to be `LIST_EXTEND` (see https://github.com/python/cpython/commit/13bc13960cc83dbd1cb5701d9a59ac9b9144b205) and that one requires more deeper understanding of Pony's codebase that I currently have. @kozlovsky @amalashkevich ideas?

**Comment by spl0k** [comment]
@kozlovsky @sashaaero are there any plan to support Python 3.9? Seeing as this PR or other py3.9-related issues got no answer from the @ponyorm team is starting to get me worried.

FWIW the following makes the array test go green, but I have absolutely no clue if this is even remotely correct (as ignoring the popped items feels wrong).
```python
    def LIST_EXTEND(decompiler, i):
        l = decompiler.stack.pop()
        decompiler.pop_items(i)
        return l
```

The remaining failing test seems to be related to the wording of an exception message so I didn't bother.

**Comment by socketpair** [comment]
https://github.com/python/cpython/blob/master/Doc/library/dis.rst

image

**Comment by socketpair** [comment]
I did not manage to trigger this opcode:

```
In [5]: dis(lambda: [].extend([1,2,3]))                                                                                                                                      
  1           0 BUILD_LIST               0
              2 LOAD_METHOD              0 (extend)
              4 LOAD_CONST               1 (1)
              6 LOAD_CONST               2 (2)
              8 LOAD_CONST               3 (3)
             10 BUILD_LIST               3
             12 CALL_METHOD              1
             14 RETURN_VALUE

In [6]: dis(lambda: [*(1,2,3)])                                                                                                                                              
  1           0 LOAD_CONST               1 ((1, 2, 3))
              2 BUILD_LIST_UNPACK        1
              4 RETURN_VALUE

In [7]: dis(lambda: [*(1,2,3), *(4,5,6)])                                                                                                                                    
  1           0 LOAD_CONST               1 ((1, 2, 3))
              2 LOAD_CONST               2 ((4, 5, 6))
              4 BUILD_LIST_UNPACK        2
              6 RETURN_VALUE

In [8]: dis(lambda: [*(1,2,3), *(4,5,6)] + [5,6,7])                                                                                                                          
  1           0 LOAD_CONST               1 ((1, 2, 3))
              2 LOAD_CONST               2 ((4, 5, 6))
              4 BUILD_LIST_UNPACK        2
              6 LOAD_CONST               3 (5)
              8 LOAD_CONST               4 (6)
             10 LOAD_CONST               5 (7)
             12 BUILD_LIST               3
             14 BINARY_ADD
             16 RETURN_VALUE
```

**Comment by socketpair** [comment]
https://github.com/python/cpython/commit/13bc13960cc83dbd1cb5701d9a59ac9b9144b205

**Comment by socketpair** [comment]
```
>>> dis(lambda: (f for f in Foo if [10, 20, 50] in f.array1))
  1           0 LOAD_CONST               1 (<code object <genexpr> at 0x7fe9fc4a30e0, file "<stdin>", line 1>)
              2 LOAD_CONST               2 ('<lambda>.<locals>.<genexpr>')
              4 MAKE_FUNCTION            0
              6 LOAD_GLOBAL              0 (Foo)
              8 GET_ITER
             10 CALL_FUNCTION            1
             12 RETURN_VALUE

Disassembly of <code object <genexpr> at 0x7fe9fc4a30e0, file "<stdin>", line 1>:
  1           0 LOAD_FAST                0 (.0)
        >>    2 FOR_ITER                24 (to 28)
              4 STORE_FAST               1 (f)
              6 BUILD_LIST               0
              8 LOAD_CONST               0 ((10, 20, 50))
             10 LIST_EXTEND              1
             12 LOAD_FAST                1 (f)
             14 LOAD_ATTR                0 (array1)
             16 CONTAINS_OP              0
             18 POP_JUMP_IF_FALSE        2
             20 LOAD_FAST                1 (f)
             22 YIELD_VALUE
             24 POP_TOP
             26 JUMP_ABSOLUTE            2
        >>   28 LOAD_CONST               1 (None)
             30 RETURN_VALUE
>>> 

```

**Comment by spl0k** [comment]
I'm getting it just by building lists larger than 2 elements

```
Python 3.9.0 (default, Oct  6 2020, 02:47:17) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dis import dis
>>> dis(lambda: [1, 2, 3])
  1           0 BUILD_LIST               0
              2 LOAD_CONST               1 ((1, 2, 3))
              4 LIST_EXTEND              1
              6 RETURN_VALUE
>>> dis(lambda: [1, 2])
  1           0 LOAD_CONST               1 (1)
              2 LOAD_CONST               2 (2)
              4 BUILD_LIST               2
              6 RETURN_VALUE
```

**Comment by socketpair** [comment]
```diff
--- a/pony-0.7.13/pony/orm/decompiling.py
+++ b/pony-0.7.13/pony/orm/decompiling.py
@@ -454,6 +454,26 @@ class Decompiler(object):
         throw(InvalidQuery('Use generator expression (... for ... in ...) '
                            'instead of list comprehension [... for ... in ...] inside query'))
.
+    def LIST_EXTEND(decompiler, i):
+        if i != 1:
+            throw(InvalidQuery('what1 %d?' % i))
+        c = decompiler.pop_items(i)[0]
+        if not isinstance(c, ast.Const):
+            throw(InvalidQuery('what2 ?? %r' % c))
+
+        if not isinstance(c.value, tuple):
+            throw(InvalidQuery('what3 ?? %r' % c.value))
+
+        # return + ast.List(t.elts)    ???
+        # pop empty array from decompiler, and replace with this one ?
+        l = decompiler.stack.pop()
+        if not isinstance(l, ast.List):
+            throw(InvalidQuery('what4 ?? %r' % l))
+
+        # TODO: check if every item of c.value is not a container (like tuple or set)
+        #       see LOAD_CONST comment
+        return ast.List(l.nodes + tuple(ast.Const(i) for i in c.value))
+
     def LOAD_ATTR(decompiler, attr_name):
         return ast.Getattr(decompiler.stack.pop(), attr_name)
.
@@ -462,6 +482,11 @@ class Decompiler(object):
         return ast.Name(freevar)
.
     def LOAD_CONST(decompiler, const_value):
+        # Since python 3.8: (1, 2, (3, 4, (5, 6))) is also SINGLE const.
+        # So we have to wrap every "constant" to ast.Const recursively (!)
+        # In [40]: dis(lambda x: (1,(2,3)))
+        #   1           0 LOAD_CONST               1 ((1, (2, 3)))
+        #               2 RETURN_VALUE
         return ast.Const(const_value)
.
     def LOAD_DEREF(decompiler, freevar):
--- a/pony-0.7.13/pony/orm/tests/test_declarative_exceptions.py
+++ b/pony-0.7.13/pony/orm/tests/test_declarative_exceptions.py
@@ -157,7 +157,8 @@ class TestSQLTranslatorExceptions(unittest.TestCase):
         select(s for s in Student if s.dob < date(s.id, 1, 1))
     @raises_exception(ExprEvalError, "`max()` raises TypeError: max() expects at least one argument" if PYPY else
                                      "`max()` raises TypeError: max expected 1 arguments, got 0" if sys.version_info[:2] < (3, 8) else
-                                     "`max()` raises TypeError: max expected 1 argument, got 0")
+                                     "`max()` raises TypeError: max expected 1 argument, got 0" if sys.version_info[:2] == (3, 8) else
+                                     "`max()` raises TypeError: max expected at least 1 argument, got 0")
     def test31(self):
         select(s for s in Student if s.id < max())
     @raises_exception(TypeError, "Incomparable types 'Student' and 'Course' in expression: s in s.courses")
```

**Comment by socketpair** [comment]
Same with sets:
```
>>> dis(lambda: a in {1, 2, (1, 2)})
  1           0 LOAD_GLOBAL              0 (a)
              2 LOAD_CONST               1 (frozenset({1, 2, (1, 2)}))
              4 CONTAINS_OP              0
              6 RETURN_VALUE
>>> dis(lambda: {1, 2, 3})
  1           0 BUILD_SET                0
              2 LOAD_CONST               1 (frozenset({1, 2, 3}))
              4 SET_UPDATE               1
              6 RETURN_VALUE
```

**Comment by kozlovsky** [comment]
Thank you, I make decompiler fixes in 91c8f655 and merged your setup fixes in dea19b2e

**Comment by socketpair** [comment]
@kozlovsky what about nested tuples ?

if user write `(f for f in Foo if [10, 20, (50, 60)] in f.array1))` there will be BUG. because 50 and 60 will ne be wrapped with `ast.Const`

**Comment by kozlovsky** [comment]
@socketpair the value attribute of `ast.Const` node should contain a native Python object and not another `ast.Const` node.

Saying that you are indeed right that expressions like `(x, y) in ((a, b), (c, d))` were processed incorrectly. I fixed it in the next commit 6fb91bd8

**Comment by socketpair** [comment]
@kozlovsky 

`values = tuple(ast.Const(v) for v in items.value)` is buggy then. Is not it ? so as far as I understand it should be either

`values = items.value`
or 
`values = wrap_to_const_recursive(items.value)`

**Pull request closed without merging**
