### PR TITLE
Microsoft SQLServer Provider 

### PR DESCRIPTION
**Pull request by giter**
I would maintain this provider.

### CODE REVIEW

**Comment by toasteez** [comment]
@amalashkevich has Microsoft  SQL Server been integrated in current pony release?

**Comment by rubenvde** [comment]
Why is this still an open pull-request? Would be nice to have an implementation of Microsoft SQLServer in PonyORM in my opinion.

**Comment by giter** [comment]
waiting too long,  let's end this request.

**Comment by bendog** [comment]
It's a pity this never went through, is there an alternative method for getting it to work with MS SQL?

**Comment by rubenvde** [comment]
Sadly only Sqlalchemy actively supports MS SQL right now

**Comment by mosesontheweb** [comment]
I also see this as a disadvantage. Would also like to see it in PonyORM as well, got sick of using SA.

**Pull request closed without merging**
